### ISSUE TITLE
`project` doesn't seem to be connected to anything? (Using deps-diff in a monorepo)

### ISSUE THREAD

**Issue by danielcompton** [namenu/deps-diff#6]
Hi there

We're looking at using this in our monorepo which has `deps.edn` files at locations like `app/deps.edn`. Is there a way to configure deps-diff to work with this setup? I saw that there was a `project` parameter which sounded like what we wanted, but it didn't appear to be used anywhere else?

https://github.com/namenu/deps-diff/blob/d91bd64e12f453bb8807a655c2a4d185ed5768d6/action.yml#L13-L16

**Comment by namenu** [comment]
I haven't tested this with monorepo, but I'll try it with our polylith repository.
Thanks for the issue.

**Comment by namenu** [comment]
Could you try `namenu/deps-diff@6f7bb72e66639a82c18e6efd5d766e3ece5c034f`
`:project` should be the complete path of deps.edn, the same as tools.deps.

Escaping action syntax to nested bash->clojure quotation was very esoteric,
and now I remember why I didn't finish that time. 😓

**Comment by danielcompton** [comment]
I got an error when I ran that:

```
Error generating tree: Local lib my/lib not found: <path>/lib
```

I think the issue is that when you have `app/deps.edn` with a dependency of

```
{:deps {org.clojure/clojure {:mvn/version "1.11.1"}
        my/lib {:local/root "../lib"}}}}
```

the `../lib` is evaluated from the relative to the caller, not relative to the `app/deps.edn` file itself. This seems like a tools.deps bug to me.

**Comment by namenu** [comment]
Good! Then I will merge this and let tools.deps handle that.

**Comment by namenu** [comment]
Finally, [TDEPS-256](https://clojure.atlassian.net/jira/software/c/projects/TDEPS/issues/TDEPS-256) has landed on maven.
In the meantime, anew option `:dir` also introduced which is more intuitive way to specify project root.
Now deps-diff use :dir instead of :project.
